### ISSUE TITLE
set_encode img

### ISSUE THREAD

**Issue by maiopirata** [openresty/set-misc-nginx-module#31]
Hello,

we would like to encode in base64 an image served by nginx.
We succesfully compile nginx and all.

I have an internal location for all my (wanted encoded pictures)
```
    location /xyz/ {
        internal;
    	alias /;
        set_encode_base64 $a;
    }
```
I assume that this set_encode will take the payload and encode it into the $a variable.
How can I say to this extension to set_encode the image and send me the encoded one?

Thanks

**Comment by agentzh** [comment]
@maiopirata Maybe you should use the ngx_lua module for this?

**Comment by maiopirata** [comment]
thank you for the answer. I thought that set_encode.. was perfect for my need but eventually I was wrong.
I will check ngx_lua.

**Comment by agentzh** [comment]
@maiopirata See also

https://github.com/openresty/nginx-eval-module
