### ISSUE TITLE
How does set_rotate keep track of the previously generated value?

### ISSUE THREAD

**Issue by jsardas** [openresty/set-misc-nginx-module#33]
Hello,

Given that the `set_rotate` directive has to keep track of the last/previously generated value each time it runs again (as opposed to `set_random`), how is this saved by Nginx? Does it involve any disk i/o (i.e. temporary file) or is it saved directly in memory? The reason why I ask this is to evaluate the impact of using set_rotate in production with different kinds of servers.

Thanks!

**Comment by agentzh** [comment]
@jsardas It is in memory only. No file I/O nor syscalls involved. And it's shared in an nginx worker process for each `location {}` block in `nginx.conf`.
