### ISSUE TITLE
compatibility with  nginx 1.12

### ISSUE THREAD

**Issue by vijaykumarchettiar** [openresty/set-misc-nginx-module#38]
Hello,
I have compiled these two dynamic modules with nginx 1.12 version. However I don't see any impact on this. Will this support nginx 1.12?

please confirm

thanks & regards
vijaykumar v

**Comment by agentzh** [comment]
@vijaykumarchettiar Yeah, it should work with nginx 1.12.x, officially. I've updated the docs to reflect this:

https://github.com/openresty/set-misc-nginx-module/#compatibility
