### ISSUE TITLE
Trouble MD5ing $request_body

### ISSUE THREAD

**Issue by matan129** [openresty/set-misc-nginx-module#40]
I'm using OpenResty and trying to hash the `$request_body` for caching purposes (with [srcache](https://github.com/openresty/srcache-nginx-module)).
I notices some problems with the cache key generation, so I started to debug it with some `echo`s.

When trying to just echo the `$request_body`, it works flawlessly:

```nginx
# actually echoes the request body
location /works {
    # force loading the body
    echo_read_request_body;

    echo $request_body;
}
```

But when trying to calculate the md5, I get the MD5 for an empty string, although I ensure the `$request_body` is loaded via `echo_read_request_body;`.

```nginx
# echoes d41d8cd98f00b204e9800998ecf8427e, which is the MD5 for empty input.
location /doesnt-work-md5 {
    # force loading the body
    echo_read_request_body;

    set_md5 $digest $request_body;
    echo $digest;
}
```

The weirdest phenomenon is that it doesn't even work when just trying to copy the variable:

```nginx
# echoes nothing - empty data
location /doesnt-work {
    # force loading the body
    echo_read_request_body;

    set $temp $request_body;
    echo $temp;
}
```

I'm not sure if I'm misusing `echo`, the `set_md5` directive or nginx itself.

By the way, these latest snippets don't work when using `$echo_request_body` instead of `$request_body`.

I'd be glad for any insight on this.
Thanks in advance!

**Comment by agentzh** [comment]
@matan129 You won't get the value in the corresponding nginx variables when the request body is buffered on the *disk*. Read the documentation for those nginx variables for more details.

**Comment by matan129** [comment]
I did read the documentation. I am not convinced disk buffering is the reason for this issue.

This happens even when sending extremely small requests bodies which are not buffered to disk. 

Even if we assumed the request body is buffered to disk, there is still no apparent reason for difference between the responses of the first and last clauses in my question.

**Comment by agentzh** [comment]
@matan129 You need to enable and check out your nginx debugging logs to be sure.

**Comment by agentzh** [comment]
@matan129 OK, I had a closer look at your example, and found that it is another mistake you make: `echo_read_request_body` always runs after `set` or `set_md5` directives no matter how you arrange their order of appearance in nginx.conf. Better look at my nginx tutorials on the running order of nginx config directives before trying to write nontrival nginx.conf of your own to save your time (and also ours):

https://openresty.org/download/agentzh-nginx-tutorials-en.html

**Comment by agentzh** [comment]
@matan129 BTW: `echo_read_request_body` runs in the "content" phase of nginx's request processing while `set` and `set_md5` both run in the "rewrite" phase. And "rewrite" phase always runs before "content" phase. Hopefully it is now clear to you.

**Comment by matan129** [comment]
Okay, thanks for the clarification.
