### ISSUE TITLE
 set-misc-nginx-module v0.33 compatible with nginx 1.15?

### ISSUE THREAD

**Issue by MuthuChess** [openresty/set-misc-nginx-module#65]
Hi Guys,

I could see the recent update v0.33. 

1. Please let me know if this version has been tested with nginx 1.15? What is the minimum/maximum nginx compatible version for v0.33? Which version of nginx do you recommend?

2. Which version of NDK do you recommend with v0.33?

Regards,
Muthu.

**Comment by xiaocang** [comment]
Hi, @MuthuChess 

> Meanwhile while I was checking the commit for this, I found that it was changed from 1.19.9 while testing. So I assume this package is also tested against 1.19.9. Is it recommended to use nginx 1.19.9 also?

We always recommend using a newer version of nginx that we have tested, if not for any other reason, I currently recommend using 1.19.9

> I am adding this module to the nginx docker container.
`./configure --add-dynamic-module=/usr/src/ngx_devel_kit-0.3.1 --add-dynamic-module=/usr/src/set-misc-nginx-module-0.33`

Yes, this option will allow others to easily compile dynamic modules to be loaded into nginx shipped in the package.
